### ISSUE TITLE
QR scanner not effective on small phone

### ISSUE THREAD

**Issue by MrHash** [LN-Zap/zap-android#106]
The current QR code scanner is not seen as a square and not working for reading payment requests on an S4 Mini. I know this phone can do better scanning as other apps can scan correctly. Is there some way to improve this? thanks

- Zap version: 0.2.5-alpha
- Android version: 9 (Pie)
- Device: Samsung S4 Mini
- LND Version: 0.7.1-beta

**Comment by JurGi7** [comment]
I have the same Problem with Sony Xperia XZ1 Compact

- Zap 0.2.5-alpha
- Android 9
- Sony Xperia XZ1 Compact
- LND 0.7.1-beta

**Comment by michaelWuensch** [comment]
Hi, 
Thanks for your reports.
The QR-Code scanner library we use seems to have problems with some models.
Unfortunatelly the only way to fix this is by changing the library and redoing the whole scanning stuff.
As several people mentioned this and it is a key feature, we hope we can do it soon.
Sorry for the inconvenience.

**Comment by MrHash** [comment]
What are the alternative impls you would consider? Maybe i can try it on a fork.

**Comment by MrHash** [comment]
i tried this simple solution and it worked for me: https://github.com/dm77/barcodescanner/issues/489

Perhaps you could test it out on more devices?

**Comment by MrHash** [comment]
See changes here: https://github.com/MrHash/zap-android/commit/c66fa74fc0b3bc4e5f3389b12fadeccfbdbe7287

Can make a PR if required.

**Comment by michaelWuensch** [comment]
Hi MrHash,
That would be an easy fix.
What exactly do you mean with: "The current QR code scanner is not seen as a square"?
And is that also fixed now?

The other complaints about the qr-code scanner were mostly when scanning the enormously dense connection qr code. I am not sure if this is the same issue, though.

**Comment by MrHash** [comment]
I used `mScannerView.setSquareViewFinder(true);` to make the scanner area a square. I was seeing a rectangle before. I couldn't scan a regular LN invoice QR before but with these changes i can.

**Comment by michaelWuensch** [comment]
Cool, thank you, sounds awesome!
Can you make a PR (without the styling changes)?
I right now don't have acces to my development pc, but I will test it on the weekend and will see if this has any negative effects on devices it worked before.

**Comment by MrHash** [comment]
ok will do! I was hoping to sneak in the slight styling change because on a smaller screen the large border and rounded corners occupy a lot of screen space and obscure the view. Anyway you can adjust that later if you agree.

**Comment by michaelWuensch** [comment]
Ah ok, I don't own such a small device, can you send a screenshot? (You might have to allow screenshots in the settings)

**Comment by MrHash** [comment]
Here is a side-by-side comparison.

![Screenshot_20190927-135150_Zap_Debug](https://user-images.githubusercontent.com/390925/65770776-b270e880-e12e-11e9-9a5b-cd2e944ffdaa.png)

![Screenshot_20190927-135336_Zap_Debug](https://user-images.githubusercontent.com/390925/65770793-bc92e700-e12e-11e9-92e8-fb271c6ce1c0.png)

**Comment by michaelWuensch** [comment]
Okay, the borders look really fat on that display. I think we have to adjust that value depending on screen pixel density. I will have a look at this, thanks for pointing it out!

**Comment by michaelWuensch** [comment]
In the next version the stroke width should now look the same on all devices and will be somewhere inbetween your 2 screenshots.

**Comment by michaelWuensch** [comment]
Fixed in 0.2.6
