### ISSUE TITLE
404 when clicking on "Need help?" button for connect to remote node

### ISSUE THREAD

**Issue by sixside** [LN-Zap/zap-android#107]
## Description

Clicking on Get Help links results in a 404 page in the local browser.

## Expected Behavior

I presume it should open up this URL: https://docs.zaphq.io/

## Actual Behavior

It opens this URL: https://ln-zap.github.io/zap-tutorials/ which is a 404 page.

## Possible Fix

Swap out the help URLs for the correct one.

## Steps to Reproduce

1. From the home screen click the orange 'Setup Wallet' button
2. Choose a PIN
3. Confirm the PIN from Step 2 
4. Click 'Connect to Remote Node'
5. Click 'Need help?' button. 

Can also replicate by going to Settings > Need Help?

## Context

Trying to figure out how to pay my first Lightning invoice and testing out a few clients.

## Your Environment

Using Zap version  on Android. I

- Zap version: 0.2.5-alpha Build 1
- Android version: 10
- Device: Google Pixel XL
- LND Version: not connected

**Comment by michaelWuensch** [comment]
Hi sixside,
Thanks for trying Zap and your detailed report.
With the launch of the new website this link got broken. We already fixed it in the code though, so it will be working again with the next update.

**Comment by michaelWuensch** [comment]
Fixed in 0.2.6
