### ISSUE TITLE
Sync Paymentrequest expiry with Desktop/iOS

### ISSUE THREAD

**Issue by maraph** [LN-Zap/zap-android#116]
## Description

Currently the user can chose expiry rates for their requests from 10 minutes up to 24 hours.
On Desktop e.g. they can chose from 1 minute to 1 year.

## Context
Current values on Desktop

![image](https://user-images.githubusercontent.com/11649986/66123218-ca8ab100-e5e1-11e9-879e-44570975afc9.png)

## Possible Implementation
Update the current values.

**Comment by michaelWuensch** [comment]
In our current codebase we already support one minute to a year. Actually we have all values plus "30 min" and "6 hours"

**Comment by maraph** [comment]
Nice, I already forgot about that one. Has been done with: #99
