### ISSUE TITLE
Zap fails to pay "private" LN invoices

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-android#121]
I can't pay invoices created from the breez wallet. Their nodes are private. Essentially, Zap for android can't pay any invoice for which the fee is unknown. It says no path to destination. The same invoice can be paid no problem with the desktop version of Zap for windows, connected to the same LND node.

- Zap version: (e.g. 0.2.5-alpha)
- Device: (Samsung Galaxy S8)
- LND Version: ( 0.7.1-beta)

**Comment by JimmyMow** [comment]
@Relaxo143 I'm having a hard time reproducing this issue, I was able to pay a private invoice without any problems.

But, if Desktop was able to pay, then surely there is some issue. Any further context you think is relevant definitely post here

**Comment by Relaxo143** [comment]
@JimmyMow Currently I'm unable to reproduce it either, because at the moment there doesn't seem to be a path for real.

 I noticed that when I wasn't able to pay with mobile, but could pay with desktop, the mobile app was behaving weirdly. It would randomly show that the server is not responding, but if I switched between history "history" and "wallet" the normal screen with the balance would show up again. LND was running and accessible the entire time, desktop had no problems. 

Besides, when I tried to create invoices (request payments) from mobile it said "error creating an invoice". Again I could request from desktop. When I clicked on "Pay" and then "paste" a red error message would show which said "error, channel close invoked" or something similar, can't remember exactly. No channels were opened nor closed, desktop showed no errors.

I tried with both wifi and mobile data. The app just seemed to throw random errors and to not even try to process a payment. Let me know if I can help you with the debugging somehow.

**Comment by Relaxo143** [comment]
I made a video which demonstrates the issue: https://youtu.be/DkuuodvYW4k

**Comment by michaelWuensch** [comment]
Strange. We will try to find that issue. Thanks for all your help so far!

**Comment by Relaxo143** [comment]
You're welcome! The described erros seem to be gone in the newest version. Still can't pay private invoices though.

**Comment by maraph** [comment]
Hey @Relaxo143, thanks for the video!
I think I found an issue with the fee calculation in case of private channels. 
Would you be willing to test the fix? 
If yes you can contact me in the zap slack `@raph` or I can also contact you by email.

**Comment by Relaxo143** [comment]
@maraph I would gladly test it. My email is: Relaxo143@protonmail.com

**Comment by Relaxo143** [comment]
@maraph Testing was successful. I am now able to pay those invoices, however the errors and weird behaviour described above are still present. Restarting Zap fixes them. I think they have something to do with [this](https://github.com/LN-Zap/zap-desktop/issues/2941) issue I opened since they started appearing around that time.

**Comment by JimmyMow** [comment]
@Relaxo143 I was able to get to the bottom of this issue and come up with a fix. @maraph will get something in and we will get a release out 👍
