### ISSUE TITLE
Inability to alter IP after LndConnect QR code scan

### ISSUE THREAD

**Issue by tukac** [LN-Zap/zap-android#138]
After scanning QR code there is no possibility to change IP address (iOs app has this option, Android app doesn't). Scanning QR takes 127.0.0.1 as IP (although I have --tlsextraip set correctly in lnd), but I want to access my lnd externally. Same happens in iOs app, but there is possibly to correct IP manually. Here IP can't be altered.

Please ad possibility to alter IP manually. Thanks!

**Comment by michaelWuensch** [comment]
Thanks for your feedback!
We will see what we can do.
In the meantime you can scan the qr code with an ordinary qr code scanner, copy/paste the result in a text editor, edit the IP there, copy the edited version and then use the past button on the connect screen. Hope this helps! :)

**Comment by tukac** [comment]
I've edited and pasted string  Thanks! :)

If I can suggest one thing. Maybe it would be good  idea to show how much of total balance is on-chain and how much is on lightning. Also lightning receiving capacity (total, single largest).

Great job!  👍

**Comment by michaelWuensch** [comment]
Glad it helped!
You can make a long press on the balance to see that.
It will later be like on iOS, it was just a quick solution to provide something at least.
