### ISSUE TITLE
Feature request: LNURL

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-android#159]
It`s like a LN address! No need to create invoices every time.

**Comment by michaelWuensch** [comment]
@Relaxo143 Thanks for creating the issue. We already planned to support this in the future :wink:

**Comment by jackeveritt** [comment]
https://github.com/LN-Zap/zap-iOS/issues/338

**Comment by michaelWuensch** [comment]
LNURL support has been released in v0.3.1-beta
The release includes support for LNURL-Pay, LNURL-Withdraw & LNURL-Channel

**Comment by rootzoll** [comment]
@michaelWuensch Is the LNURL-Withdraw supporting the FALLBACK-URL scheme? Its one of the first things mentioned on the LNURL-Spec and should just be a few lines of code to support: https://github.com/btcontract/lnurl-rfc#fallback-scheme

I tried to scan a LNURL-FALLBACK-URL and Zap said: "Unkown Data"

**Comment by michaelWuensch** [comment]
@rootzoll 
No, LNURL-Fallback is not yet supported.
Added to the todo list! :)
