### ISSUE TITLE
Zap build cannot be verified

### ISSUE THREAD

**Issue by Giszmo** [LN-Zap/zap-android#161]
[I tried to verify the build](https://walletscrutiny.com/posts/zapsolutions.zap/) from Google Play against the source code but got a diff in binary files.
Could you please investigate and improve the build instructions so the releases can be verified.

I think this is highly important also for internal use, as the release manager under distress might put the users' funds at risk and only deterministic builds allow the team to react.

**Comment by michaelWuensch** [comment]
@Giszmo 
Thanks for doing this. This is indeed very important.
We generate two APKs so we can keep the download size at a minimum.
I don't know though why the diffs appear.
I always built it using Android Studio, but that shouldn't make a difference, I think.
We have to investigate this and will inform you if we have any news on this.

**Comment by Giszmo** [comment]
@michaelWuensch thanks for your interest and understanding. Yes, I was surprised that not more apps were building multiple APKs but yours was the first and only one I remember. We failed to compile some apps, so ... who knows.

Sorry for boring you with my problems but would you have an idea how to get all APKs as they get released? My best idea is a monitor app that hopefully one user per category (architecture, country, screen size, ...) runs on their phone to hash every relevant apk and check my server if we know that one and if not, upload it.

**Comment by michaelWuensch** [comment]
@Giszmo 
I used the following firefox extension which allows you to download all the apks from google play store:
https://addons.mozilla.org/en-US/firefox/addon/direct-apk-downloader-2018/
I am not sure though if this really helps to automate this in a feasible way.

I now also started to investigate the diffs.
I found out that the 2 json files for example only differ in linebreaks

**Comment by Giszmo** [comment]
The line breaks in json and the png diffs I would have allowed for now, although later I would need some criteria that can be automated, so finding a careful balance to what is allowed in a diff and what might open the door for malicious insertions would be a tricky one. My main concern are the .so files.

For the png files you would have to disable pngcrunch. You can run it once and commit the crunched files to avoid the compile time non-determinism.

Thanks for the firefox tip. If the extension can download apks, console tools can, too.

**Comment by Giszmo** [comment]
Three months later ... is there any progress regarding verifiability?

**Comment by githorray** [comment]
> @Giszmo
> Thanks for doing this. This is indeed very important.
> We generate two APKs so we can keep the download size at a minimum.
> I don't know though why the diffs appear.
> I always built it using Android Studio, but that shouldn't make a difference, I think.
> We have to investigate this and will inform you if we have any news on this.

Is there a reason the 0.3.1 release doesn't include the APK's?

**Comment by raphBTC** [comment]
Hey @githorray,
no reason other than I have forgot to, have attached them now.

**Comment by Giszmo** [comment]
Attaching a build to GitHub releases is unrelated to this issue. How is the issue coming along?

**Comment by michaelWuensch** [comment]
@Giszmo 
We have not forgotten about it. There is still so much left to do on Zap Android that we just didn't take the time to investigate further where this diffs come from. Eventually we will tackle this issue as well.
In the meantime everyone who does not trust us has the possibility to build it from source.

**Comment by michaelWuensch** [comment]
I know it is important. But usability is as well.
There is no use in having a verifiable wallet if it is complicated to use and people flock to a custodial wallets instead.
It is a question of priority.

Just so you can better understand me: 
You are the only one so far who asked for verifiability (which actually surprises me), while we get lots of other requests.
This means it might not be the top priority for everyone.

If more people ask for it, I will prioritize this above other things.
And if not I will still try to make it verifiable, but it might take some time.

By the way, I don't feel like i owe anything to anyone. I am doing this 100% for free in my spare time. Nobody is forced to use Zap Android.

**Comment by Giszmo** [comment]
Well, ... I'm working on getting more people up to speed on the topic. Non-techies that learn about open source, assume that that is enough and that somehow magically thousands of security researchers review code of any tiny project.

Re: What you owe: This project is open source under the MIT license, so you the software developer don't owe anything to anybody and I totally agree with that. You do put the binary out there through Google Play though, where you make at least implicit promises of this app being good to use. From that angle, I see a big duty to provide certain levels of security and not knowing how the binary came to be, is scary.

**Comment by sangaman** [comment]
I'm a zap user and would like to see this as a priority. Without reproducibility it's not much different from closed source software.

**Comment by michaelWuensch** [comment]
@Giszmo 
Hi, I want to get this done now, but have problems to find out, what causes the differences.
If I do a fresh clone of the Source Repo and build a unsigned version with
$ ./gradlew assembleRelease
And right after that create again a unsigned version with:
$ docker run --rm -it --volume=$PWD:/mnt --workdir /mnt mreichelt/android:latest bash
root@84c836f4577a:/mnt# ./gradlew assembleRelease

And compare the two results with:
diff --brief --recursive BuiltOnPC/ BuiltWithDocker/

I get this as result:
Dateien BuiltOnPC/lib/armeabi-v7a/libiconv.so und BuiltWithDocker/lib/armeabi-v7a/libiconv.so sind verschieden.
Dateien BuiltOnPC/lib/armeabi-v7a/libzbarjni.so und BuiltWithDocker/lib/armeabi-v7a/libzbarjni.so sind verschieden.

All other differences seem to have vanished, but the .so files still differ. (Both are unsigned, therefore the signing differences are gone as well.) 
The only difference in the build process seems to be building with the docker image vs building with Android Studio installed from the official website.
Do you have any idea what could cause this or how to proceed from here?

**Comment by Giszmo** [comment]
Hallo Michael!

Nice to hear you are working on this! So those two native libs are built in a non-deterministic way and there are several things that might cause this. I would check in this order:

* Do those libraries have dependencies that are not pinned to one specific version?
* Are the build tools pinned to a specific version?
* Try with disorderfs. Many projects process files in folders in the order the underlying file system provides them and that causes non-deterministic results. Disorderfs is a thin FS layer that allows to control the sorting.

**Comment by michaelWuensch** [comment]
@Giszmo 
Thanks for your help.
I found out, that both .so files are part of the QR-Code scanner library I used. 
Luckily I have made a PR on a new QR-Code scanner library a long time ago but did not merge it, as it didn't really make a difference. With this library the app seems to be 0.6 mb smaller though and no longer has those .so files.
So I think the easiest way is to make some last improvements on that PR and merge it.
I will try that first.

**Comment by michaelWuensch** [comment]
@Giszmo 
I just released a new version (v0.3.8-beta) which should be reproducible. It will probably take some time until it is available on the playstore though. On github the release is already available.
Please note that it is now only one apk and no longer two. This will later change again though, when local LND is added.
Please let me know if it worked.

This should be the instructions you will need to reproduce it:

$ cd zap-android/
$ git tag | grep 0.3.8
v0.3.8-beta
$ git checkout v0.3.8-beta 
$ docker run --rm -it --volume=$PWD:/mnt --workdir /mnt mreichelt/android:latest bash
root@84c836f4577a:/mnt# ./gradlew assembleRelease
root@84c836f4577a:/mnt# mv app/build/outputs/apk/release/zap-android-0.3.8-beta* .
root@84c836f4577a:/mnt# exit
$ ls *.apk
'zap-android-0.3.8-beta(26)-release-unsigned.apk'

**Comment by Giszmo** [comment]
> Please note that it is now only one apk and no longer two. This will later change again though, when local LND is added.

Can you please elaborate?

Compilation is quick and works. I don't have the Google Play version yet though.

**Comment by michaelWuensch** [comment]
@Giszmo 
It is now available on google play as well. Hope it works and we have reproducible Zap for Christmas :)

> Can you please elaborate?

I changed the QR-Code scanner library which removed the .so files. Appearently after that change the splitted apks were all identical, as there was no architecture specfic code anymore.
Google play even recognized all that apks as ABI "all". So I actually had to make it build a single one again with a higher store id, to ensure all devices get updated.
Later, when local lnd is added, we will most likely switch back to a splitted deploy, as it reduces the app size a lot when we don't include all the different architectures of lnd.

**Comment by Giszmo** [comment]
[Welcome in the top ranks](https://walletscrutiny.com/android/zapsolutions.zap/)!

That split part will make things complicated on my end as I don't have many channels to obtain binaries.  I will approve the rebuild for one of those, only and it will get a bit a pain to get all architectures to broaden the checks.
