### ISSUE TITLE
A paid invoice for amounts larger than the original request is not showing as paid in zap

### ISSUE THREAD

**Issue by thorie7912** [LN-Zap/zap-android#165]
## Description

In zap i created an invoice for 52000 sats. I then sent payment to that invoice using phoenix wallet but I clicked send all funds which was 52467 sats. It was sent successfully 

But in zap, the 52000 invoice still shows unpaid and there's no other receipt of money.

When i switch to zeusln connected to the same lnd node, it does show the receipt of 52467 sats.

## Expected Behavior

Should see the payment, even if the amount doesn't match the invoice.

## Actual Behavior

Invoice shown as unpaid.

## Steps to Reproduce

1. Create an invoice for some amount X in zap
2. Pay that invoice with X + additional amount
3. Check zap
4. See invoice not paid

## Your Environment

- Zap version: 0.2.11-alpha
- Android version: _(e.g. API 28)_
- Device: LGv20
- LND Version: 0.9.0

**Comment by michaelWuensch** [comment]
Hi @thorie7912 
thanks for the report.
I was quite busy with my job lately, so sorry for the delay.
I have found the issue and made a PR for it #170

**Comment by michaelWuensch** [comment]
This has been fixed and it was shipped in v0.3.0
