### ISSUE TITLE
Better can't connect to node error handling

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-android#17]
I tested the new error message when trying to connect to a remote node by pasting in poor `lndconnect` data. It worked great!

I think an improvement would be displaying the error, not in the wallet UI. In order for me to try again (inputting lndconnect data) I had to go to `Settings` -> `Reset` -> `Setup remote node`. Maybe instead we display the error in the initial setup screen?

**Comment by michaelWuensch** [comment]
The error messages are much more detailed now.
