### ISSUE TITLE
Generated on-chain address

### ISSUE THREAD

**Issue by ftt01** [LN-Zap/zap-android#178]
## Description

On Android application version 0.2.11-alpha, the generated address for receiving funds on-chain contain "bitcoin:" at the beginning. This is useless, it is copied to clipboard when the address is copied.

## Expected Behavior

The shown address could contains "bitcoin:", but not the copied one.

## Actual Behavior

Both shown and copied bitcoin on-chain generated address have "bitcoin:" at the beginning.

## Steps to Reproduce

To reproduce on Android app, version 0.2.11-alpha

1. Receive
2. On-chain
3. Next
4. Generate request
5. Copy or Details

## Your Environment

Android 9
Zap 0.2.11-alpha

- Zap version: _0.2.11-alpha_
- Android version: _9_
- Device: _Motorola Z3_
- LND Version: _Not connected_

**Comment by Relaxo143** [comment]
Why would you want something to be shown, but not copied? "bitcoin:" is part of the standard Bitcoin URI which most wallets recognize. More info here: https://en.bitcoin.it/wiki/BIP_0021
I agree that if you need only the address itself "bitcoin:" is not needed, but it's pretty easy to delete that part once pasted. However if you specify an exact amount for the payment the Bitcoin URI becomes very useful.  
Maybe the devs could remove "bitcoin:" from the string if no amount is specified, but it's up to them to decide.
