### ISSUE TITLE
Remote Connection via TOR

### ISSUE THREAD

**Issue by bmml1** [LN-Zap/zap-android#185]
Connection via TOR not working. Somewhat related to https://github.com/LN-Zap/zap-iOS/issues/333

## Description

Following this [tutorial](https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md) for connecting ZAP with remote lightning Node via Tor. 
Orbot is running in VPN Mode and ZAP is enabled for VPN mode.

## Expected Behavior

Working connection via TOR

## Actual Behavior

Error Message: Tor Connection failed.... 
btw: where can one extract more information / debug log?

## Steps to Reproduce

1. enable restlisten=localhost:8080 in lnd.conf
2. create tor hidden service
3. create qr code with lndconnect and hiddenservice url
4. scan qr code in app

## Your Environment

-    Zap version: 0.2.11-alpha
-    Android version: Android 10 (LineageOS)
-    Device: OnePlus3
 -   LND Version: 0.92

**Comment by michaelWuensch** [comment]
Zap Android does not support connection using REST. Zap Android uses gRPC on port 10009
Can you try it with that port forwarded?

**Comment by bmml1** [comment]
So Torrc file looks like:
HiddenServiceDir /var/lib/tor/lnd/
HiddenServiceVersion 3
HiddenServicePort 10009 127.0.0.1:10009

Lnd conf
rpclisten=0.0.0.0:10009

then:
lndconnect --host=12345test.onion --port=10009

Am I missing something?

**Comment by michaelWuensch** [comment]
Maybe. 
Are you sure you have forwarded 10009 on your router?
To be honest I haven't setup a tor node myself so far, I just tested with someone elses already setup node. And there it worked.
Hopefully I will find the time to setup one myself soon.
In the meantime maybe @raphBTC can help you. As far as I know, he already did this, but he is quite busy right now, so that might also take a while.

**Comment by bmml1** [comment]
I think the port forwarding is not necessary via Tor. Nevertheless I guess there is something missing in one of the config files.

**Comment by mrfelton** [comment]
@bmml1 can you try also setting `tlsextradomain=12345test.onion` in your lnd config and regenerate your tls certs and lndconnect string

**Comment by bmml1** [comment]
@mrfelton thanks for the reply. 

I added tlsextradomain with onion adress from lnd hidden service to the config, regenerated the certificates(deleting *.tls files, restarting lnd daemon and double checking the certificate with openssl x509 -in /path/to/cert/ -text). 

I then started orbot in vpn mode(with zap enabled), started zap and scanned the newly generated qr-code from lndconnect with no success. 

It says tor connection failed please check that:
Orbot runs
Orbot runs in vpn mode
Zap is activated for vpn mode

It is however possible to reach the hidden service via TOR Browser on my pc. When accepting security hint for the self signed certificate it offers to download a file of type application/grpc which seems correct?!

Any more ideas?

btw zap version is now 0.3.0 beta(was  0.2.11-alpha) in original post(if that matters)

**Comment by michaelWuensch** [comment]
@bmml1 @mrfelton 
Not a solution, but I just tested again to access @mrfelton's tor test node.
I used Zap Android 0.3.0 with orbot and the tor node is running LND 0.9.1.
It worked. So I don't think it is an issue that is related to the Zap version or the LND version.

**Comment by bmml1** [comment]
I removed and readded the zap app in orbot. It works now. Thx! @michaelWuensch @mrfelton
