### ISSUE TITLE
Timeout when trying to connect to lnd on mynode via tor

### ISSUE THREAD

**Issue by maxwedwards** [LN-Zap/zap-android#191]
I have LND running on a mynode on a RPi 4 with 4GB of ram connected to a slow spinning rust usb HDD. It's pretty slow as it is but when I connect to it over tor it's extremely slow. 10s of seconds to load admin pages but does get there.

I'm trying to connect the Zap wallet over tor and it's timing out. The error message appears quite quickly and from experience of using the admin interface over tor, it feels too quick for how slow that connection is. I can be waiting 30+ seconds for page loads. It takes 15 seconds when not using tor.

Could I propose a longer timeout when tor is being used?

- Zap version: 0.3.0-beta (build 18)
- Android version: Android 10
- Device: OnePlus 6T
- LND Version: 0.9.2

**Comment by michaelWuensch** [comment]
Hi,
thanks for the report. I actually needed to do this some time ago when I was testing local LND on low end devices. Forgot to also update that in the main project.
My PR increases the timeout from 10 to 30 seconds and should be in the next release.
