### ISSUE TITLE
Too generic error message makes it impossible to solve connection problems

### ISSUE THREAD

**Issue by Kixunil** [LN-Zap/zap-android#202]
## Description

When there's a problem with connecting to a node, the error message tells few generic options instead of telling **specific** reason why the connection failed

## Expected Behavior

See single, **specific** error message when the connection fails.

## Actual Behavior

All theoretically possible errors are shown

## Possible Fix

Show only one message based on cause of error

## Steps to Reproduce

1. Create lndconnect QR code with some setting intentionally broken (e.g. bad hostname)
2. Scan the QR code
3. See error

## Context

I'm trying to connect to a lnd node and can't figure out why it doesn't work. `nc hostanme 10009` connects, so there must be something else screwed up and there's no tool to find out.

## Your Environment

- Zap version: 0.3.0-beta
- Android version: 10
- Device: Google Pixel 3
- LND Version: 0.10.0-beta

**Comment by michaelWuensch** [comment]
Hi,
yes, this can be improved.
Thanks for your input!
