### ISSUE TITLE
Regtest builds?

### ISSUE THREAD

**Issue by Kixunil** [LN-Zap/zap-android#233]
Is it possible to build a regtest version of the app? If yes, it'd be nice to document it, if not I'd like to see it enabled.

## Description

I'd like a special version of the app using regtest instead of mainnet. Similarly to how Eclair mobile app has a testnet version (well testnet would be nice too, but I personally find regtest more practical). This version should accept all regtest inputs (addresses, invoices...) and reject mainnet inputs. It should be graphically distinct from mainnet version so that people don't get confused if they install them side-by side.
It'd be extra nice to have this version available in the Play store or at least pre-built APK somewhere online.

## Context

I need to quickly iterate testing of my integrations an lately I started to use regtest much more. It's much more convenient as it doesn't start automatically downloading 300GB of chain and I don't need to care about risking real money for some advanced test cases. This helps with development of software, especially creating software with less bugs.

## Possible Implementation

When it comes to distinguishing from mainnet I'd suggest a different color scheme  together with word "regtes" somewhere in the UI.

Off topic: I've noticed you implemented LNURL - very useful feature, thanks a lot!

**Comment by michaelWuensch** [comment]
This is something I wanted to do for a long time...
I will try to make this work next week for builds from source.

**Comment by michaelWuensch** [comment]
Regtest support was merged. Please see the documentation here:
https://github.com/LN-Zap/zap-android/blob/master/docs/REGTEST.md

**Comment by Kixunil** [comment]
Awesome, thanks!
