### ISSUE TITLE
Feature request: Custom fee rates for channel openings

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-android#249]
I used the app to open a channel and got burned with 10k sats fee. Some users might not be in a rush so an option to specify feerates would be great. I believe in LND that's done with 
-sats_per_byte

**Comment by bmml1** [comment]
@michaelWuensch This would be a nice feature. Does anything speak against it?

**Comment by michaelWuensch** [comment]
@bmml1 
No, nothings speaks against it just takes time to do it.
If anyone wants to make a PR I would be more than happy ;-)

**Comment by michaelWuensch** [comment]
This is done now and will be released with the next version!

**Comment by michaelWuensch** [comment]
shipped with v0.4.0-beta
