### ISSUE TITLE
Support management of multiple wallets in Zap android

### ISSUE THREAD

**Issue by michaelWuensch** [LN-Zap/zap-android#25]
The user should be able to create and manage more than one wallet with Zap. 
For example a wallet running directly on the phone and a wallet on a node that is remote controlled with Zap. There has to be a easy way to switch between wallets without overcomplicating the UI for all the users that just have one wallet.

**Comment by Kixunil** [comment]
This would help me a lot - I could manage my own finances as well as finances of organization I'm involved in.
