### ISSUE TITLE
LNURL is not working as expected 

### ISSUE THREAD

**Issue by jetlagv1** [LN-Zap/zap-android#257]
LNURL from the satsback program by stekking.com won't go through when opened in zap on Android. 

## Description
I've had two payouts and both were recognized from the clipboard by zap as soon as I opened the app but ended in an error saying LNURL is no longer valid.
The same LNURL did work in bluewallet so I'm using that now for payouts but it also confirms that it's not the LNURL but zap wallet that seem to have this problem.

## Expected Behavior

The LNURL should go work with zap so that the payments can be received. 

## Actual Behavior

LNURL get recognized but end in an error message "LNURL is no longer valid" 

## Steps to Reproduce

1. Have a LNURL in the clipboard and open zap. 
2. Zap asks if you want to import the LNURL.
3. Accept. 
4. You then see the payment but when you continue it fails. 

## Context

I was trying to receive a payment from the stekking.com satsback program. 

## Your Environment

- Zap version: 0.3.3 beta build: 2021
- Android version: 10
- Device: oneplus-7-pro 
- LND Version: 0.10.4-beta

**Comment by michaelWuensch** [comment]
Thanks for the report!
"LNURL is no longer valid" sounds like that LNURL was already executed.
Just to be sure... 
Did you first try Zap, then got the error message and then pasted the exact same thing into bluewallet and it worked?
Or did you do something in a different order? Or did you rerequest payout on stekking before trying bluewallet?

**Comment by jetlagv1** [comment]
I did exactly that. It would not go through using zap so I then tried
bluewallet and it went through straight away.
I have another LNURL from stekking.com that gives the same issue. I did not
yet try that one in another wallet to for testing purposes. I can either
give you the LNURL to try or I can wait for a while till the issue is
fixed. But I have to claim the payout withing 30 days.

**Comment by michaelWuensch** [comment]
@jetlagv1 
Ok, strange.
If you could give me the LNURL that might help me to debug. If I get it to work and the payment goes through I will of course give you the money back.
Can you send the LNURL to michael90@protonmail.com?

**Comment by jetlagv1** [comment]
You've got mail..

**Comment by michaelWuensch** [comment]
This is now fixed and will be released with the next version.
Thanks for reporting!
