### ISSUE TITLE
Channel created via Lightning Pool mentioned as force closed in history

### ISSUE THREAD

**Issue by cryptoteun** [LN-Zap/zap-android#267]
## Description
I have ZAP Android wallet connect to my own lnd node ([link](https://1ml.com/node/020c5c96420bb2dddfd0a19d26bfa30f9e6335174c0ce3bd7754b852bb5cbe333a)). 

Today I was experimenting with Lightning pool to get inbound capacity. 
- An order was executed and channel ([721397275668250624](https://1ml.com/channel/721397275668250624)) was created
- This was via transaction ([636f1292fb11f8b82ed354a1b953080cb38efd6bc4f0acd3869d07437873f5af](https://blockstream.info/tx/636f1292fb11f8b82ed354a1b953080cb38efd6bc4f0acd3869d07437873f5af))

This channel is fully operational and ZAP Android is showing this in the Channel List. But in the history only one item is shown:
- Channel Force closed

## Expected Behavior
Channel should be shown correctly in the History. 

## Actual Behavior
Channel shown as force closed.

## Possible Fix
-

## Steps to Reproduce
See description

## Context
See description

## Your Environment
- Zap version: 0.3.5 beta build 2023
- LND Version: 0.11.1-beta

**Comment by michaelWuensch** [comment]
Hi there,
thanks for the report, that sounds odd. I will look into this.
Is it still displayed as force closed and still working?

**Comment by michaelWuensch** [comment]
Hi, 
I am so far unable to reproduce this.
All my test show newly created channels correctly in the history list.
Is there only shown one entry in your history list (force closed) for that channel, or are there shown two (opened channel & force closed channel)?

**Comment by cryptoteun** [comment]
It's indeed the only one showing. 

The channel is closed at the moment via a cooperative close. So that worked fine as well.
