### ISSUE TITLE
Missing support for BIP21 URI with lightning= parameter

### ISSUE THREAD

**Issue by Kixunil** [LN-Zap/zap-android#269]
Zap does not appear to support BIP21 URIs with `lightning=` parameter.

## Description

According to LN standards `bitcoin:someaddress&lightning=invoice` is a valid string that allows for backwards-compatible QR code. However Zap does not support this. This leads to significantly degraded user experience. Recent implementation of this feature in BTCPayServer may increase popularity of this feature so it's better to solve it soon.

## Expected Behavior

After scanning a QR code with BIP21 URI and `lightning=` parameter the user is requested to confirm the payment and then a payment over LN is attempted. If the payment fails, the user is asked whether to pay off-LN. If the user confirms, then off-LN payment is performed.

## Actual Behavior

User is requested to confirm an "On-Chain" transaction.

Note: yes, I verified that the QR code from BTCPayServer actually contains `lightning=` parameter using an external QR code reader and also successfully paid over LN using BLW.

## Possible Fix

BIP21 is a standard and Zap does not support this standard leading to bad UX therefore I believe it's a bug. The fix is to support the standard, which should be pretty easy - just check if `lightning=` is present and try to process it as invoice if it is. In case of failure, ask user about chain payment as if there was no `lightnin=` parameter. Of course a proper URI parsing should be implemented (but I guess it already is?) - no regexes searching for `lightning=`.

## Steps to Reproduce

1. create a QR code with BIP21 URI - e.g. using the newest version of BTCPayServer
2. scan the QR code with Zap

## Context

I tried to pay BIP21 Lightning invoice (thankfully on my own server to see if it works).

## Your Environment

- Zap version: latest
- Android version: 11
- Device: Google Pixel 3
- LND Version: 0.11.1 (but should be irrelevant)

**Comment by michaelWuensch** [comment]
Hi,
thanks for the issue! This will definetly take some effort to implement, especially the fallback stuff if it fails.
But I agree it would be a nice feature and I hope I'll find time to implement this soon. :)

**Comment by Kixunil** [comment]
Awesome, thanks for being quick to fix this!
