### ISSUE TITLE
Give the option to add route hints / set private flag for invoices

### ISSUE THREAD

**Issue by mandelmonkey** [LN-Zap/zap-android#274]
When creating an invoice we can flag the private flag and thus the invoice will not include route hints for private channels

## Description

A simple toggle when creating an invoice to let the user include route hints, I understand zap calls the LND make invoice rpc call, so it would just need to set ```isPrivate``` to 1 and LND will include route hints in the invoice

## Context

I use zap to connect to my LND node, however my LND node only has one private channel, when I make an invoice using Zap, the invoice cannot be paid as the sender can not find a route due to my private channel. LND allows you to set ```isPrivate``` when generating an invoice to allow routine to be possible.

Wallet such as Nayuta Core only have private channels as well as people running LND on lower end hardware or run nodes that don't want to be routing nodes all use private channels, current Zap does not work with them.

## Possible Implementation

A simple toggle when creating an invoice? or an option in advanced settings to always set private flag to true when making an invoice?

**Comment by michaelWuensch** [comment]
Hi, thanks for your feedback.
I think I'll go with the option in advanced settings, as most people won't need it.
Personally I think nodes with only private channels are a dead end for liquidity and lightning in general and should be avoided if possible.

**Comment by mandelmonkey** [comment]
For reference it's for a mobile node that has lnd running on android but
can't be a routing node as it doesn't have an open public IP address, they
use Zap as a way to connect to that node running on local host

**Comment by michaelWuensch** [comment]
@mandelmonkey I have created a PR for this now.
With this PR routing hints are enabled by default. You can disable them in the advanced settings.
Tested it on regtest and it worked.

**Comment by mandelmonkey** [comment]
Awesome, thanks!

**Comment by michaelWuensch** [comment]
I just released a new version that includes this change.

**Comment by mandelmonkey** [comment]
Great thanks for the quick turn around

**Comment by mandelmonkey** [comment]
It seems there is an edge case where the flag is not respected, when Zap receives an LNURL Withdraw Request and generates an invoice for it, it seems that the private flag is not being set?

**Comment by michaelWuensch** [comment]
@mandelmonkey 

Ah, thanks for pointing that out. I just included a fix in #308 which also makes all the private channel stuff available (when opening channels)

**Comment by mandelmonkey** [comment]
@michaelWuensch amazing thanks!

**Comment by kiwiidb** [comment]
Just wanted to say I think Zap Android wallet still does not include routing hints if you only have private channels.
- Connected to my Umbrel node
- 1 private channel, bought from Bitrefill
- Neither LNURL - withdraw nor manually created invoices seem to include routing hints
I am on the latest release from Play Store, 3/4/2021

**Comment by michaelWuensch** [comment]
@kiwiidb 
thanks for the notice, I will have a look at it again an test it.

**Comment by kiwiidb** [comment]
Upon further testing it seems the issue is with LND and not with Zap.
