### ISSUE TITLE
Channel capacity display mismatch

### ISSUE THREAD

**Issue by typtyphus** [LN-Zap/zap-android#278]
## Description
Channel capacity values on Zap are not the same as the ones I created on my node.

My node:
![IMG_20201206_102044](https://user-images.githubusercontent.com/865676/101276759-6ba96480-37af-11eb-9d9a-55454438ee8f.jpg)

Zap:
![IMG_20201206_101953](https://user-images.githubusercontent.com/865676/101276760-6c41fb00-37af-11eb-91fb-f535cf6199f6.jpg)

##  Environment
- Zap version: 0.3.5-Beta
- Android version: 10
- LND Version: 11.1-beta

**Comment by michaelWuensch** [comment]
Hi,
the reason for this is that zap subtracts the commit fee. 
To close a channel an on chain transaction has to be done. This transaction costs fees, which must be reserved.
On such small channels like in your example this is about half of the whole channel capacity.
I understand the confusion though and I am open for suggestions on how this can be improved.

Here is the reference in code:
https://github.com/LN-Zap/zap-android/blob/master/app/src/main/java/zapsolutions/zap/channelManagement/OpenChannelViewHolder.java#L32-L33

**Comment by typtyphus** [comment]
Thanks for clearing that up.

a suggestion, maybe have the closing transaction portion of the bar marked in red. I haven't tried to close a channel, but closing fees are depend on speed? Would it be possible for the closing portion to be adjustable?

I usually get things greyed-out when they are pending, you could go with that.

**Comment by michaelWuensch** [comment]
Advanced channel details were added in the last release (#360 )
This should explain it and help to understand what is going on.
