### ISSUE TITLE
Keysend payments in history

### ISSUE THREAD

**Issue by adamc199** [LN-Zap/zap-android#282]
I can no longer see keysend payments in my history on the latest release. Was this removed or am I missing something?

**Comment by michaelWuensch** [comment]
Hi,
interesting. I actually haven't done anything to support keysend payments so far.
Sending a keysend payment with Zap Android is not yet possible.
I haven't tried to receive one either.
Keysend payement support is on the list though and one of the next things to be added.

I can't think of any changes in the latest updates that would affect the history list in any way. Is it possible that you also did an LND update?
Which was the version where it worked?

**Comment by michaelWuensch** [comment]
Hi, I am closing this issue now.
I am internally testing a new version, that has keysend support and all the keysend payments are shown there.
