### ISSUE TITLE
Add the ability to flag channel as private when opening via lnurl channel

### ISSUE THREAD

**Issue by mandelmonkey** [LN-Zap/zap-android#287]
Add the ability to flag channel as private when opening via lnurl channel

## Description

When opening a channel there is no option to flag the channel as private so the channel opens as public

## Context

Our users are using LND running on mobile devices which do not have public static ips, so all channels need to be private so route hints can be added. When using a service like bitrefills thor it is not possible to open the channel as private.

## Possible Implementation

A check box to flag as private when viewing the open channel confirmation screen, or an option in settings to make all channels open as private

**Comment by mandelmonkey** [comment]
Just wondered if this request has been seen and/or considered? thanks!

**Comment by michaelWuensch** [comment]
Was doing a lot of other PRs lately. This will be one of the next, thanks for bringing up the issue.

**Comment by michaelWuensch** [comment]
shipped with v0.4.0-beta
