### ISSUE TITLE
Outbound multipart payments

### ISSUE THREAD

**Issue by Technifocal** [LN-Zap/zap-android#289]
## Description

Implement outbound multipart payments to allow `lnd` to split larger outbound payments into multiple parts.

## Context

As of current, Zap-Android outputs `Maximum Amount: ${largest_channel_local_balance}` and shows the invoice amount in red.

## Possible Implementation

Potentially add a `max_parts` configuration option into settings, or a configuration for each invoice.

**Comment by michaelWuensch** [comment]
Hi Technifocal,
thanks for the issue. It is on my list for quite some time now and one of the next things to come, so stay tuned! :)

**Comment by michaelWuensch** [comment]
Multi path payments are done now and will be shipped with the next version!

**Comment by michaelWuensch** [comment]
shipped with v0.4.0-beta
