### ISSUE TITLE
Allow to manually change Connection Data

### ISSUE THREAD

**Issue by elkimek** [LN-Zap/zap-android#298]
Allow to manually change Connection Data

In case of connecting to a port forwarded node manually changing the Connection Data is needed because the LND Connect generates a QR with original IP address. There is no way to easily change the IP to actual IP of the node.

**Comment by michaelWuensch** [comment]
Thanks for your issue.
Yes that would definetly help in some situations. I'll see what I can do.

**Comment by michaelWuensch** [comment]
This is done now and will ship in the next version!
