### ISSUE TITLE
Issue connecting to proposed channel partner ZAP Technologies

### ISSUE THREAD

**Issue by bmml1** [LN-Zap/zap-android#314]
## Description

Hello,

this is not really a Zap-Android bug, but I thought that you might be in touch with the operator of the "Zap Technologies" lnd node.

When I first installed the app I opened a channel to Zap Technologies which was proposed when opening a new channel. The channel opened without a problem(some month ago). Since a couple of days/weeks(can't say for sure) the channel state switched to "offline" (in the app) or when entering lncli listchannels it has the state `"active": false,`

I am running lnd version 0.12.1-beta

**When manually connecting to the node via:**
`lncli connect 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735`

**output of ournalctl -f -u lnd** (removed the timestamps)

```


[INF] SRVR: Established connection to: 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735
[INF] SRVR: Finalizing connection to 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735, inbound=false
[INF] PEER: NodeKey(03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf) loading ChannelPoint(ChannelPoint123456789:1)
[INF] HSWC: Removing channel link with ChannelID(ChannelID123456789)
[INF] HSWC: ChannelLink(658114:1158:1): starting
[INF] HSWC: Trimming open circuits for chan_id=658114:1158:1, start_htlc_id=0
[INF] HSWC: Adding live link chan_id=ChannelID123456789, short_chan_id=658114:1158:1
[INF] HSWC: ChannelLink(658114:1158:1): HTLC manager started, bandwidth=12345 mSAT
[INF] HSWC: ChannelLink(658114:1158:1): attempting to re-resynchronize
[INF] CNCT: Attempting to update ContractSignals for ChannelPoint(ChannelPoint123456789:1)
[INF] PEER: Negotiated chan series queries with 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
[INF] DISC: Creating new GossipSyncer for peer=03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
[INF] DISC: GossipSyncer(03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf): requesting new chans from height=0 and 672483 blocks after
[INF] PEER: unable to read message from 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735: EOF
[INF] PEER: disconnecting 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735, reason: read handler closed
[INF] DISC: Removing GossipSyncer for peer=03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
[INF] HSWC: Removing channel link with ChannelID(ChannelID123456789)
[INF] HSWC: ChannelLink(658114:1158:1): stopping
[WRN] HSWC: ChannelLink(658114:1158:1): error when syncing channel states: link shutting down
[INF] HSWC: ChannelLink(658114:1158:1): exited
```

So I searched a little bit and found this issue(the logs look similar but it is a different node) in the lnd repo which suggest that there maybe a problem when peers are running outdated lnd versions
https://github.com/lightningnetwork/lnd/issues/4941

Do you know which lnd version the Zap Technologies node is running or could you ask the operator if you know him?

Cheers!

**Comment by michaelWuensch** [comment]
@mrfelton 
Do you know what is going on or which version the ZAP Technologies node runs?

**Comment by michaelWuensch** [comment]
I have removed the suggested channel partner list from the open channel view, as it is no longer maintained.
