### ISSUE TITLE
Unable to unlock wallet with zap since lnd walletunlocker change

### ISSUE THREAD

**Issue by githorray** [LN-Zap/zap-android#315]
See https://github.com/lightningnetwork/lnd/pull/4985

Running zap-android 0.4.0 beta

Zap error: "Access denied! The macaroon is invalid. [Retry]"

After unlocking the wallet with `lncli unlock` Zap works normally.

**Comment by michaelWuensch** [comment]
Hi,
thanks for the issue. What version of LND are you using? The PR you linked to was merged only 10 days ago which means it is not yet included in the official releases.

**Comment by githorray** [comment]
using master.

**Comment by michaelWuensch** [comment]
Yes, I haven't fixed that one yet. For now you have to unlock manually or with a different app.
This will be fixed in the next release.

**Comment by michaelWuensch** [comment]
This should be fixed now with the new release (0.5.3-beta). Feel free to reopen the issue if you still have problems.
