### ISSUE TITLE
Cannot connect to LND on remote node

### ISSUE THREAD

**Issue by bitznbrewz** [LN-Zap/zap-android#334]
## Description

Zap wallet is unable to connect to LND on my Umbrel node.  The node is fully synced, has several small channels opened, and is able to connect to the Zeus wallet.  

Seems like there may be an issue with Orbot as the Zeus wallet has a built-in Tor implementation.  I think the app is unable to maintain connection to the Tor service.

## Expected Behavior

Expecting wallet balances and the like to load after establishing connection to my Umbrel node over Tor.  

## Actual Behavior

Opening the app gives 1 of 2 error messages:

"Tor connection failed" OR

"Unable to connect to LND"

## Steps to Reproduce

1.  Open Orbot
2. Toggle VPN mode to on
3. Select Zap wallet as a VPN app
4. Click start
5. Wait for network bootstrapping to complete
6. Open Zap wallet
7. Scan QR code from Umbrel node

## Your Environment

- Zap version: 0.4.1-beta
- Android version: _(e.g. API 28)_
- Device: Pixel 3
- LND Version: v0.12.1-beta
- Orbot Version: 16.4.1-RC-2-to.0.4.4.6 (from Google Play Store)

**Comment by michaelWuensch** [comment]
Hi,
thanks for your report.
Unfortunately Orbot often causes issues. Sometimes I just can't get it to work. What helps for me in this situation is to actually restart the phone (restarting Orbot and Zap is not enough). After that it works again for some days or weeks.

Integrating Tor natively is on the to do list, I hope this trick helps in the meantime.

**Comment by michaelWuensch** [comment]
I have just released v0.5.0-beta which includes native Tor support.
This should solve the Tor connection issues.
If there are still problems after the update, feel free to open a new Issue.
