### ISSUE TITLE
User opt out for connections to blockchain.info for data queries

### ISSUE THREAD

**Issue by 05nelsonm** [LN-Zap/zap-android#34]
Would prefer use of a different source for price data and what not. Currently blocking the connection using NetGuard, but would like it if I did not have to.

Or at least give the ability to connect through tor via the Orbot app in order to obfuscate our IP addresses.

**Comment by michaelWuensch** [comment]
Hi, 
which price sources would you prefer?

If you also choose a bitcoin unit as your second unit, there is no need to ask for fiat prices. But right now it still does. I will fix that. So this will be your way to opt out in the next version.

**Comment by michaelWuensch** [comment]
See my latest commit 92fd4bda2ed2ded45378af35df1b5fe91487bc2d

**Comment by mrfelton** [comment]
FYI, we are just adding this into the desktop app (see https://github.com/LN-Zap/zap-desktop/pull/2424). We chose to support price feeds from:

- coinbase
- bitastamp
- kraken
- bitfinex

**Comment by 05nelsonm** [comment]
> Hi,
> which price sources would you prefer?
> 
> If you also choose a bitcoin unit as your second unit, there is no need to ask for fiat prices. But right now it still does. I will fix that. So this will be your way to opt out in the next version.

I would love the 2nd unit being bitcoin to not proc the connection. That is smart AF, man, and quite slick.

**Comment by michaelWuensch** [comment]
Just wanted to let you know. The new version is out! If both units are bitcoin units (for example BTC and sat) the app will no longer initiate any exchangerate requests.

**Comment by 05nelsonm** [comment]
> Just wanted to let you know. The new version is out! If both units are bitcoin units (for example BTC and sat) the app will no longer initiate any exchangerate requests.

Love it!

This app is super nice btw... Great work, man!
