### ISSUE TITLE
Tor Support

### ISSUE THREAD

**Issue by 05nelsonm** [LN-Zap/zap-android#35]
Adding tor support via the Orbot app would be awesome and would allow for easier connections to personal nodes via hidden services, as well as obfuscation of mobile IP addresses when the app queries blockchain.info for Bitcoin data.

**Comment by michaelWuensch** [comment]
It is planned, but realistically not going to happen soon. Unless someone other than me is implementing it. ;-)

**Comment by 05nelsonm** [comment]
I wish I knew how to code so I could help with it... learning, though!

**Comment by JimmyMow** [comment]
@michaelWuensch @maraph has anyone looked into this one? Something like Orbot?

**Comment by 05nelsonm** [comment]
I think it's possible if zap app were to have settings that would allow it to utilize Orbot's proxy services @ 127.0.0.1:9050

Could setup a hidden service on the machine running LND node, and then just use in LND connect the .onion address.

Actually, I have some time tonight and will play around with it. Might be able to test it by running Orbot in VPN mode to force Zap to use Tor. Not sure if it'll be able to query the .onion address, though.

**Comment by michaelWuensch** [comment]
@05nelsonm have you had any success?

**Comment by 05nelsonm** [comment]
> @05nelsonm have you had any success?

No I haven't. What I tried was to:

Create a hidden service by adding to my /etc/tor/torrc:
```
HiddenServiceDir /var/lib/tor/lnd-connect
HiddenServiceVersion 3
HiddenServicePort 10009 127.0.0.1:10009
```

Restarted tor and then obtained the .onion address via:
`$ sudo cat /var/lib/tor/lnd-connect/hostname`

[Be sure to wait a bit for the .onion address to propagate throughout the Tor network]

Took my lnd-connect cert and replaced the ip address (127.0.0.1) with the .onion address

On my phone I enabled Orbot as a VPN, making sure to enable coverage of Zap Android

Reconnected Zap Android via the new lnd-connect link while on mobile data.

**Results:**

- Was unable to connect.
- Not sure if this is an issue with the torrc configuration, or if Zap Android is able to even recognize the .onion address.
- Will have to play around with it some more to try and get it to work.

**Comment by michaelWuensch** [comment]
@05nelsonm Thanks for the detailed results.
Unfortunately I have litteraly no experience with tor so far, that's why I cannot really help you.
I will have to look into this when we work on tor support.

What I do to establish the connection is building a channel with OKHttp. 
```
mSecureChannel = OkHttpChannelBuilder
                    .forAddress(host, port)
                    .sslSocketFactory(mSSLFactory)
                    .build();
```

So I guess, the question is if OkHttp can handle tor. But I don't know what Orbot is actually doing or if it helps here in any way.

**Comment by seth586** [comment]
> **Results:**
> 
> * Was unable to connect.
> * Not sure if this is an issue with the torrc configuration, or if Zap Android is able to even recognize the .onion address.
> * Will have to play around with it some more to try and get it to work.

To make sure your tor server is set up correctly, try the same workflow with [Zeus LN](https://github.com/ZeusLN/zeus/releases) android app, use 10009 tho:
```
./lndconnect --lnddir=/var/db/lnd --image --host=blahblahblahblahblahblah.onion --port=10009
```
torrc:
```
HiddenServiceDir /var/db/tor/remote_connections
HiddenServiceVersion 3
HiddenServicePort 10009 127.0.0.1:10009
HiddenServicePort 8080 127.0.0.1:8080
```
The above works for me on [Zeus](https://github.com/ZeusLN/zeus/releases) but the same workflow with port 8080 for Zap does not work.

**Comment by michaelWuensch** [comment]
Hi seth586,
yes, tor is not supported yet. We use gRPC to make all the API calls which is much more complicated to get to work with tor than REST. We probably will have to write a wrapper that falls back to REST when we connect to a tor node.
It is definetly a feature we want to support soon, but right now I don't think it is possible to connect to a tor node.

**Comment by 05nelsonm** [comment]
👀
