### ISSUE TITLE
Cannot connect after upgrade to 0.5.0

### ISSUE THREAD

**Issue by mikkoc** [LN-Zap/zap-android#356]
## Description

Cannot connect after upgrade to 0.5.0

## Expected Behavior

Should be able to connect as normal.

## Actual Behavior
The following error is shown:

`The node is reachable but returns an internal error. This error might be caused by using a wrong port.`

## Possible Fix

Downgrade? Have not tried yet.

## Steps to Reproduce

Upgrade to 0.5.0 and try to connect to the existing clearnet LND node.
Please note I use `wireguard` to connect to my server privately, I do not use TOR.

## Context

I'm unable to use ZAP at the moment.

## Your Environment

- Zap version: 0.5.0-beta
- Android version: 11
- Device: Google Pixel 4A
- LND Version: v0.13.1-beta

**Comment by michaelWuensch** [comment]
@mikkoc 
Thanks for the issue report.

Have you tried to turn of Tor in the settings? Maybe this already fixes your issue.
If that doesn't work downgrading should definetly work. You can download the older apks directly here from github in the release section.

I will have to look into wireguard (never used it so far) and see I can get it working.

Please let me know if switching of Tor in the settings works for you.

**Comment by mikkoc** [comment]
Ah, disabling Tor from the settings does solve the issue indeed, thanks!
