### ISSUE TITLE
lnd not getting new blocks from bitcoind after using Zap Android. possible rpc overload?

### ISSUE THREAD

**Issue by 05nelsonm** [LN-Zap/zap-android#36]
Thought it was docker lag causing lnd to miss new blocks as they came in at first, but after some testing I found it's got something to do with accessing lnd remotely and making rpc calls to it that seems to be hanging up communication between bitcoind and lnd clients. Initially opened a ticket over at lightningnetwrok/lnd, but am posting over here as well to link the 2. Might help with fixing.

https://github.com/lightningnetwork/lnd/issues/3205

**Comment by michaelWuensch** [comment]
Thanks for the report.
LND should be able to handle the requests, I Think. Switching between "History" and "Wallet" should only initiate 2 RPC calls everytime "Wallet" is pressed. So I guess it is unlikely to be an RPC overflow.
I hope the guys from LND will be able to track this down.

**Comment by 05nelsonm** [comment]
Have been running bitcoind on host machine as opposed to in a Docker container for a while now without issue. Going to chalk it up to that and close the issue.

**Comment by michaelWuensch** [comment]
Tahnks for the update!
