### ISSUE TITLE
No-amount-invoice error message is misleading

### ISSUE THREAD

**Issue by vindard** [LN-Zap/zap-android#363]
## Description

When trying to pay a no-amount invoice the error message received is:

> Invalid payment information.
>
> Please use a Bitcoin address or Lightning payment request to initiate a payment.

This is misleading and confusing since it suggests there is some error in the request itself and not just a business logic rule failure.

I came across this issue and thought there was a problem with the other person's wallet. I only found the problem through a mix of:
- manually decoding the invoice to double-check it was valid, and
- having prior knowledge that Zap doesn't like no-amount invoices

The error message should be more directed at the business rule.

![Screenshot_20210919-080530__01.jpg](https://user-images.githubusercontent.com/17693119/133927102-74b88b40-1299-4f5d-b31f-2ce008eb328c.jpg)

## Expected Behavior

Error message should say the invoice needs a non-zero amount.

## Actual Behavior

Error message simply says the invoice is invalid.

## Possible Fix

Change the error message to be more specific.

## Steps to Reproduce

Simply try to pay a zero-amount ln invoice.

**Comment by vindard** [comment]
I just found a similar issue/fix across in the Zap-Desktop repo: https://github.com/LN-Zap/zap-desktop/pull/3385

**Comment by michaelWuensch** [comment]
Thanks again for the issue and PR, this is merged now, so I will close it.
