### ISSUE TITLE
I can't send Bitcoin to my muun wallet

### ISSUE THREAD

**Issue by Rothschildiuk** [LN-Zap/zap-android#382]
![Screenshot_20211108-231702](https://user-images.githubusercontent.com/15833131/140827426-87856790-0897-4efc-8062-f179b78961ba.png)

**Comment by michaelWuensch** [comment]
@Rothschildiuk 
Hi, 
Zap Android is just a remote control for your LND node. The error that is displayed tells you that your node is not able to find a route for the payment.

This can happen for payments with large amounts or when your node isn't well connected.

How many open channels do you have? 
If you have just one for example it might also be that the channel peer was offline while you tried to send the payment.

**Comment by Rothschildiuk** [comment]
I have opened 12 channels. 
I can send Satoshi to my blue wallet, and then to muun wallet, but not directly to muun.
I try this last month more than 5 times.

**Comment by michaelWuensch** [comment]
That seems strange.
Have you already tried to send directly to muun with your node but without a different app?
like Zap desktop, Zeus, from cli or any other interface?
If that would work then it would be indeed a problem with Zap Android.

**Comment by Rothschildiuk** [comment]
Zeus have the same issue.:(
