### ISSUE TITLE
Cannot connect to LNURL onion host

### ISSUE THREAD

**Issue by setpill** [LN-Zap/zap-android#383]
## Description

I have a `lnd` backend only reachable through the local network. In order to use it I turned off routing all traffic through tor. When I try to open a LNURL link that is hosted via tor, it gives an error. The host is reachable through tor browser.

## Expected Behavior

It connects to and fetches the LNURL details from the server over tor.

## Actual Behavior

"[tor address].onion is not responding"

## Possible Fix

Open .onion links through tor even if "route all traffic through tor" is not enabled.

## Your Environment

- Zap version: 0.5.2-beta, build 3032
- LND Version: 0.13.1-beta

**Comment by michaelWuensch** [comment]
Thanks for the issue.

This is quite complex to change though and it would make the user interface more complicated.
I will think about it.
But I think that is actually an edge case. Zap Android is there to enable you access to you r node on the go, it doesn't make much sense to only use it at home except for testing.

**Comment by michaelWuensch** [comment]
Took a long time, but this should now be possible!
