### ISSUE TITLE
Zap suddenly crashing every time it starts

### ISSUE THREAD

**Issue by sangaman** [LN-Zap/zap-android#396]
## Description

Zap does not start. It shows the loading page and then immediately closes. This behavior persists through clearing the app storage/cache and through uninstalling and reinstalling zap. Zap worked for me on the same phone as of a few days ago.

## Your Environment

- Zap version: 0.5.3-beta
- Android version: 12
- Device: Google Pixel 4a 5g
- LND Version: 0.14.1-beta

**Comment by pcwd** [comment]
Not starting on my Pixel 5 either.  I also have Android 12 and LND v 0.14.1-beta.

**Comment by hazrulnizam** [comment]
Same here. Crashes on startup. My environment as follows:

- Zap version: 0.5.3-beta
- Android version: 12
- Device: Samsung Galaxy S21
- LND version: 0.14.1-beta

I uninstalled and reinstalled 0.5.2-beta via apk to recover functionality. Also turned off auto-update on Play Store just to be safe.

**Comment by michaelWuensch** [comment]
Hey guys,
Thanks for the feedback.
I think this only happens on Android 12, at least all of you use Android 12 so far.
I'll try to fix this as fast as possible. 
In the mean time you can downgrade manualy by downloading 0.5.2 Apk from github releases and disable the auto update.

**Comment by michaelWuensch** [comment]
I just made a new release (0.5.4-beta). It is not live yet on google play though.
Can someone download this release from github and confirm if it works? I have no Android 12 device to test.

**Comment by hazrulnizam** [comment]
I tested 0.5.4-beta apk on my Android 12. It works!

**Comment by pcwd** [comment]
Yep 0.5.4.beta works on my Pixel 5 with Android 12.

**Comment by michaelWuensch** [comment]
Thanks guys! Then I'll release on google play as well :)

**Comment by sangaman** [comment]
Confirmed that 0.5.4 works for me, thanks!
