### ISSUE TITLE
Address shown on Zap transaction page is what?  It's not my wallet address?

### ISSUE THREAD

**Issue by jkaldon** [LN-Zap/zap-android#406]
I recently sent a significant amount of money to the address listed on the transaction history.  It's truly unclear what that address is or how it relates to me...but it's definitely not my on-chain btc wallet address.  Unfortunately, I didn't catch this myself because the address shown here was very similar to my actual btc wallet address.

It may not be a bug, per-say, but it really screwed me and I fear others will have the same problem.

I would like to see some clarification on the UI explaining that this address is not the user's btc wallet address.

I have no idea what this address being shown is.  Maybe if I knew, there might be some way for me to get my money back from that address?

I'm not sure there is much else to explain.

1. Transfer money on-chain to your btc wallet 
2. Open the transaction in zap.
3. See the address and see that it is not your btc wallet address.

## Context

I was trying to put money into my wallet using mercuryo.io.

## Your Environment

- Zap version: Zap 0.5.5-beta build: 3035
- Android version: Android version 12
- Device: Samsung Galaxy S20 FE 5G
- LND Version: v0.14.2-beta

**Comment by michaelWuensch** [comment]
@jkaldon 
Hi, thanks for your report and really sorry for the issue.
I am a little bit confused. The screenshot looks like it is from Zap Desktop, not Zap Android.

To find the issue and help you, I need the information from the fist transaction that generated the History entry and from the second transaction that got send to the unknown address.
Do you have the transaction IDs?
If you want to do this via PM you can join the zap slack and PM me there. (Zaphq.slack.com)

**Comment by jkaldon** [comment]
> @jkaldon Hi, thanks for your report and really sorry for the issue. I am a little bit confused. The screenshot looks like it is from Zap Desktop, not Zap Android.
> 
> To find the issue and help you, I need the information from the fist transaction that generated the History entry and from the second transaction that got send to the unknown address. Do you have the transaction IDs? If you want to do this via PM you can join the zap slack and PM me there. (Zaphq.slack.com)

Sorry for the confusion... but, yes, the problem exists in both the desktop and android apps.

I went to Zaphq.slack.com, but it doesn't let me sign up.  When I log in, it offers to sign me into my other slack channels.  Sorry, I haven't used slack in a couple of years.  Do I need an invite?

**Comment by michaelWuensch** [comment]
@jkaldon 
Hm, I am not the creator of that Zap Slack space and also not that experienced with slack....
Maybe it is easier if we do it by mail. I just created a new e-mail address you can use to contact me, as I don't want to post my official one :)
michaelprivatesupport@protonmail.com

**Comment by michaelWuensch** [comment]
This is now fixed in v0.5.6-beta.
