### ISSUE TITLE
Host cannot be resolved....

### ISSUE THREAD

**Issue by Rothschildiuk** [LN-Zap/zap-android#412]
I have last umbrel Ln node, and today I received the following error message.

Host (*****.onion)
cannot be resolved,
Please update your wallet connection settings if your node is now reachable under a different address or hostname.

- Zap version: 0.5.6-beta
- Android version: 12 
- Device: Google Pixel 5
- LND Version: v0.14.2-beta

**Comment by michaelWuensch** [comment]
Hi,
did it work before?
If yes, did an update of Zap or an update of umbrel break it?
I am using it myself with umbrel without problems.

**Comment by ybaidiuk** [comment]
umbrel 14.18 
Zap version: 0.5.6-beta

Same issue. 
Yes it worked before well. 
get "Host cannot be resolved" and "connection failed"

**Comment by ybaidiuk** [comment]
> I have last umbrel Ln node, and today I received the following error message.
> 
> Host (*****.onion) cannot be resolved, Please update your wallet connection settings if your node is now reachable under a different address or hostname.
> 
> * Zap version: 0.5.6-beta
> * Android version: 12
> * Device: Google Pixel 5
> * LND Version: v0.14.2-beta

I restarted umbrel and now it works...
