### ISSUE TITLE
Minor: Force closing channel results in wrong total being displayed

### ISSUE THREAD

**Issue by zechendorf** [LN-Zap/zap-android#67]
The total Satoshi's displayed is off, when force closing a channel.

## Description

I had to force close a channel (via Zap desktop) to a peer. That transaction (because of the timelock) is now - of course - in limbo until the timelock is passed. The Zap desktop still shows the correct total, but on the Zap Android wallet the total is missing the amount from my forced close.

It's a bug since it differs from the actual amount and from what is being displayed by Zap desktop.

## Expected Behavior

Force closing a channel should not impact the amount of Satoshi's in total.

## Actual Behavior

The "local balance* of the force closed channel is missing in the total.

## Possible Fix

Don't deduct force closed channels from the total.

## Steps to Reproduce

1. Send some BTC to your wallet
2. Open a channel with size X, wait till it's confirmed
3. Force close the channel
4. The total Satoshi's being displayed is missing X

## Context

Minor display error.

## Your Environment

BTCPayServer, Zap Android

- Zap version: 0.2.3-alpha
- Android version: 9
- Device: Google Pixel 3
- LND Version: 0.7.0-beta

**Comment by maraph** [comment]
Hello @zechendorf,
thanks for reporting this issue. 🥇 

We are going to investigate it and will keep you updated!

**Comment by maraph** [comment]
Hey @zechendorf,

the fix has been merged and should be shipped within the next release.
Thank you for bringing it up 👏

**Comment by zechendorf** [comment]
Thank you! Didn't expect it to get fixed this fast!
